# Agenda, day 2

1. Q&A
2. Data frames
    - Create them
    - Indexes and column names
    - Retrieving and setting
    - Methods and attributes we'll want to use
    - `.loc` and mask indexes
3. Creating data frames from files
    - CSV files
    - Excel
    - JSON
    - Retrieving data from the Internet

# Data frames

If a series is a 1D data structure (with values and an index), then a data frame is a 2D data structure, much like an Excel spreadsheet. It also has an index (identifying the rows) and columns (identifying the ... columns).

Each column in a data frame is actually a series in disguise!

In [1]:
# quick and dirty creation of a data frame, using a list of lists

import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])

In [3]:
df

     0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

- Rows are 0,1,2,3
- Columns are 0, 1, 2

This is because we didn't name them.

Notice also that it's OK for the rows and columns to have the same names (or in this case, numbers).

In [4]:
df.index   # show me the rows

RangeIndex(start=0, stop=4, step=1)

In [5]:
df.columns  # show me the columns

RangeIndex(start=0, stop=3, step=1)

In [6]:
# I might want to set either the index or the column names
# we saw with a series that we can pass index= and then a list
# the same is true with a data frame, except we can also say columns= and give a list of column names

df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [7]:
# just like with a series, we can retrieve via the index using .loc (and .iloc, by position)

df.loc['a']

x    10
y    20
z    30
Name: a, dtype: int64

In [8]:
df.loc['c']

x    70
y    80
z    90
Name: c, dtype: int64

In [9]:
# I can even use fancy indexing to get more than one row

df.loc[['a', 'c']]  # pass a list of indexes for fancy indexing

    x   y   z
a  10  20  30
c  70  80  90

In [10]:
# I can even use a slice

df.loc['a':'c']   # no inner list here, because it's a slice

    x   y   z
a  10  20  30
b  40  50  60
c  70  80  90

In [11]:
# I can still use my friend iloc, to go by location

df.iloc[0]

x    10
y    20
z    30
Name: a, dtype: int64

In [12]:
df.iloc[2]

x    70
y    80
z    90
Name: c, dtype: int64

In [14]:
df.iloc[[0, 2]]

    x   y   z
a  10  20  30
c  70  80  90

In [15]:
df.iloc[0:2]  # unlike .loc, this is up to and *not* including, as per Python in general

    x   y   z
a  10  20  30
b  40  50  60

# But ... what about the columns?

We can retrieve from columns using `[]`. That is, if you use `.loc`, you get rows (via the index). But if you use `[]`, you get columns. 

This is why I told you last week not to use `[]` to retrieve rows, because you'll get confused.

In [16]:
df['x']  # this returns the x column in df

a     10
b     40
c     70
d    100
Name: x, dtype: int64

In [17]:
# can I use fancy indexing with columns? Yes!

df[['x', 'z']]   # list inside of []

     x    z
a   10   30
b   40   60
c   70   90
d  100  120

In [18]:

df = DataFrame([[10, 20.1, 30],     # list of lists
                [40, 50.2, 60],
                [70, 80.3, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x      y    z
a   10   20.1   30
b   40   50.2   60
c   70   80.3   90
d  100  110.0  120

In [19]:
df.dtypes  # what dtypes do we have?

x      int64
y    float64
z      int64
dtype: object

In [20]:
# what happens if I now retrieve row a?

df.loc['a']   # we get a series back, with a dtype of float64 -- the integers were silently changed for this temporary, in-memory series

x    10.0
y    20.1
z    30.0
Name: a, dtype: float64

# Exercise: Grocery store

1. Create a data frame describing products in a grocery store. The columns will be `product` (a string), `price` (an int), and `department` (also a string).
2. Add 5 products in your store. Each product will be one row in your data frame.
3. Retrieve the products at positions 0 and 3.
4. Retrieve just the `price` column. What is the mean price of items in your store?

In [21]:
df

     x      y    z
a   10   20.1   30
b   40   50.2   60
c   70   80.3   90
d  100  110.0  120

In [22]:
df.values

array([[ 10. ,  20.1,  30. ],
       [ 40. ,  50.2,  60. ],
       [ 70. ,  80.3,  90. ],
       [100. , 110. , 120. ]])

In [24]:
df = DataFrame([['apple', 5, 'produce'],
                ['bananas', 3, 'produce'],
                ['computer', 500, 'electronics'],
                ['diary', 20, 'books'],
                ['elephant', 100, 'pets']],
               index=[123, 456, 789, 234, 678],
               columns='product price department'.split())
df

      product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets

In [25]:
df.dtypes

product         str
price         int64
department      str
dtype: object

In [26]:
df.iloc[[0, 3]]

    product  price department
123   apple      5    produce
234   diary     20      books

In [28]:
df.loc[[123, 234]]

    product  price department
123   apple      5    produce
234   diary     20      books

In [29]:
df['price']

123      5
456      3
789    500
234     20
678    100
Name: price, dtype: int64

In [30]:
df['price'].mean()   # invoke the mean method on a series

np.float64(125.6)

# Another way to retrieve columns

I much (MUCH) prefer to retrieve columns in this way, as I've shown you, with `[]`. But there is another way, namely dot notation. Just put the name of the column after the name of the data frame and a dot, as if it's an attribute of the data frame.

In [32]:
df.price

123      5
456      3
789    500
234     20
678    100
Name: price, dtype: int64

In [33]:
df.department

123        produce
456        produce
789    electronics
234          books
678           pets
Name: department, dtype: str

In [34]:
df.product

<bound method DataFrame.prod of       product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets>

Dot syntax works great, until/unless:

- Your column has the same name as a Pandas method or attribute, in which case the Pandas value gets priority over yours
- If the column contains spaces or other characters that aren't legal in Python attribute names, then they won't work

# What if I want to assign a new column to our data frame?

We can do this by assigning to a new column in the data frame -- just make sure that it has the right number of elements.

In [35]:
df

      product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets

In [36]:
df['letter'] = ['a', 'b', 'c', 'd', 'e']   #adds a new column

In [37]:
df

      product  price   department letter
123     apple      5      produce      a
456   bananas      3      produce      b
789  computer    500  electronics      c
234     diary     20        books      d
678  elephant    100         pets      e

In [38]:
# what happens if I try to add a column with the wrong number of values?

df['letter2'] = ['a', 'b', 'c', 'd']

ValueError: Length of values (4) does not match length of index (5)

In [39]:
df

      product  price   department letter
123     apple      5      produce      a
456   bananas      3      produce      b
789  computer    500  electronics      c
234     diary     20        books      d
678  elephant    100         pets      e

# What if you want to replace an existing column with other values?

Answer: Just assign to the column. The new one will replace the old one.

In [40]:
df['letter'] = ['aaa', 'bbb', 'ccc', 'ddd', 'eee']   # because we're assigning to an existing column, it is replaced

In [41]:
df

      product  price   department letter
123     apple      5      produce    aaa
456   bananas      3      produce    bbb
789  computer    500  electronics    ccc
234     diary     20        books    ddd
678  elephant    100         pets    eee

Many times, we'll want to do this to calculate values based on existing columns.

In [42]:
tax_rate = 0.1

df['price'] * tax_rate    # series * a scalar = broadcasting

123     0.5
456     0.3
789    50.0
234     2.0
678    10.0
Name: price, dtype: float64

In [43]:
df['product_tax'] = df['price'] * tax_rate

In [44]:
df

      product  price   department letter  product_tax
123     apple      5      produce    aaa          0.5
456   bananas      3      produce    bbb          0.3
789  computer    500  electronics    ccc         50.0
234     diary     20        books    ddd          2.0
678  elephant    100         pets    eee         10.0

In [45]:
df['total_price'] = df['price'] + df['product_tax']

In [46]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [48]:
df2 = df.copy()   #get a copy of df's data, but without sharing it

In [49]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [50]:
df2

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [52]:
df2['total_price'] = df2['price'] + df2['price'] + df2['product_tax']

In [53]:
df2

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5         10.5
456   bananas      3      produce    bbb          0.3          6.3
789  computer    500  electronics    ccc         50.0       1050.0
234     diary     20        books    ddd          2.0         42.0
678  elephant    100         pets    eee         10.0        210.0

In [54]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [55]:
# the assign method adds a new column to a temporary data frame that it returns

In [56]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

# More complex queries

Let's say that I want to retrieve from my data frame based on a particular column's values -- but I don't want that column's values, rather I want to use one column as my mask index, and retrieve from another.

For example, I want the mean price of all items with a product_tax > 5.

The way to do this is with `.loc`, the 2-argument edition.

- The first argument to `.loc` (mandatory) is the row selector
    - one index value
    - a list of index values ("fancy indexing")
    - a slice
    - a boolean series for use as a "mask index"
- The second (optional) argument to `.loc` is a column selector
    - one column name
    - a list of column names

In [57]:
df.loc[123, 'department']   # row selector = 123, column selector = 'department'

'produce'

In [59]:
# I'm going to spread these out, using "method chaining"

(
    df
    .loc[
        123,              # index, the row selector
        'department'      # column name, the column selector
    ]

)

'produce'

In [61]:
# I can ask for more than one row


(
    df
    .loc[
        [123, 456],        # index, the row selector -- fancy indexing
        'department'      # column name, the column selector
    ]

)

123    produce
456    produce
Name: department, dtype: str