# Agenda, day 3

1. Q&A
2. Sorting
3. Grouping (basic, advanced)
4. Pivot tables
5. Joining
6. Data cleaning
7. Plotting (using the Pandas API)
8. AMA (ask me anything)
9. What's next?

# Sorting

What does it mean to sort our data?

- We want to order it, usually from smallest to largest, but sometimes from largest to smallest
- When we're talking about sorting data in Pandas, we can sort in many different ways

Why do this?

- We often want the smallest and largest values
- These values can be interersting or point to trends
- Ordering the data is required for certain actions -- e.g., getting the median

In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv('taxi.csv',          # load the CSV file taxi.csv into a data frame (with 10k taxi records)
                 index_col=['tpep_pickup_datetime'])   # the pickup datetime column should be our data frame's index

In [3]:
df

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-02 11:19:29,2,2015-06-02 11:47:52,1,1.63,-73.954430,40.764141,1,N,-73.974754,40.754093,2,17.0,0.0,0.5,0.00,0.0,0.3,17.80
2015-06-02 11:19:30,2,2015-06-02 11:27:56,1,0.46,-73.971443,40.758942,1,N,-73.978539,40.761909,1,6.5,0.0,0.5,1.00,0.0,0.3,8.30
2015-06-02 11:19:31,2,2015-06-02 11:30:30,1,0.87,-73.978111,40.738434,1,N,-73.990273,40.745438,1,8.0,0.0,0.5,2.20,0.0,0.3,11.00
2015-06-02 11:19:31,2,2015-06-02 11:39:02,1,2.13,-73.945892,40.773529,1,N,-73.971527,40.760330,1,13.5,0.0,0.5,2.86,0.0,0.3,17.16
2015-06-02 11:19:32,1,2015-06-02 11:32:49,1,1.40,-73.979088,40.776772,1,N,-73.982162,40.758999,2,9.5,0.0,0.5,0.00,0.0,0.3,10.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-01 00:12:59,1,2015-06-01 00:24:18,1,2.70,-73.947792,40.814972,1,N,-73.973358,40.783638,2,11.0,0.5,0.5,0.00,0.0,0.3,12.30
2015-06-01 00:12:59,1,2015-06-01 00:28:16,1,4.50,-74.004066,40.747818,1,N,-73.953758,40.779285,1,16.0,0.5,0.5,3.00,0.0,0.3,20.30
2015-06-01 00:13:00,2,2015-06-01 00:37:25,1,5.59,-73.994377,40.766102,1,N,-73.903206,40.750546,2,21.0,0.5,0.5,0.00,0.0,0.3,22.30
2015-06-01 00:13:02,2,2015-06-01 00:19:10,6,1.54,-73.978302,40.748531,1,N,-73.989166,40.762852,2,6.5,0.5,0.5,0.00,0.0,0.3,7.80
2015-06-01 00:13:04,1,2015-06-01 00:36:33,1,5.80,-73.983215,40.726414,1,N,-73.924133,40.701645,1,21.0,0.5,0.5,4.45,0.0,0.3,26.75

In [4]:
# what was the sortest trip distance that someone has in our data set?

df['trip_distance'].min()

np.float64(0.0)

In [5]:
# what about the 5 shortest trips?
# I can sort the values using sort_values

df['trip_distance'].sort_values()

tpep_pickup_datetime
2015-06-01 00:12:13     0.00
2015-06-04 15:18:09     0.00
2015-06-02 11:23:46     0.00
2015-06-01 00:08:03     0.00
2015-06-01 00:07:43     0.00
                       ...
2015-06-04 15:17:25    34.84
2015-06-02 11:21:03    35.51
2015-06-01 00:02:42    37.20
2015-06-01 00:04:50    60.30
2015-06-01 00:00:58    64.60
Name: trip_distance, Length: 9999, dtype: float64

In [6]:
# once I've sorted the values, I can then use head/tail to get the top/bottom rows

df['trip_distance'].sort_values().head(5)   # these are the 5  smallest values for trip_distance

tpep_pickup_datetime
2015-06-01 00:12:13    0.0
2015-06-04 15:18:09    0.0
2015-06-02 11:23:46    0.0
2015-06-01 00:08:03    0.0
2015-06-01 00:07:43    0.0
Name: trip_distance, dtype: float64

In [7]:
df['trip_distance'].sort_values().tail(5)

tpep_pickup_datetime
2015-06-04 15:17:25    34.84
2015-06-02 11:21:03    35.51
2015-06-01 00:02:42    37.20
2015-06-01 00:04:50    60.30
2015-06-01 00:00:58    64.60
Name: trip_distance, dtype: float64

In [8]:
# you could argue that using head/tail is a waste -- why not just use .iloc?

df['trip_distance'].sort_values().iloc[:5]

tpep_pickup_datetime
2015-06-01 00:12:13    0.0
2015-06-04 15:18:09    0.0
2015-06-02 11:23:46    0.0
2015-06-01 00:08:03    0.0
2015-06-01 00:07:43    0.0
Name: trip_distance, dtype: float64

In [9]:
df['trip_distance'].sort_values().iloc[-5:]   # using negative indexing + slicing from Python

tpep_pickup_datetime
2015-06-04 15:17:25    34.84
2015-06-02 11:21:03    35.51
2015-06-01 00:02:42    37.20
2015-06-01 00:04:50    60.30
2015-06-01 00:00:58    64.60
Name: trip_distance, dtype: float64

`sort_values` does *not* change our data frame, or the series that we're running on. It returns a new series back, based on the original column, but not changing it at all.

# We can also sort by the index!

Sometimes, you don't want to sort the data frame (or a column from it) by the values. Rather, you want to sort by the index. For example, in our data frame, the index contains dates and times. If we want the 10 earliest trips in the data set, we can sort by the index, and then do a `head(10)` or `[:10]`.

For that, we use the `sort_index` method. This returns a new series, based on the original one, sorted from smallest to largest, looking at the index.

In [13]:
df['trip_distance'].sort_index()

tpep_pickup_datetime
2015-06-01 00:00:00     1.00
2015-06-01 00:00:00     1.40
2015-06-01 00:00:00     0.90
2015-06-01 00:00:01     8.15
2015-06-01 00:00:01     1.20
                       ...
2015-06-06 16:53:56     1.20
2015-06-06 16:53:56     1.30
2015-06-06 16:53:56    17.36
2015-06-06 16:53:56     0.58
2015-06-06 16:53:57     0.50
Name: trip_distance, Length: 9999, dtype: float64

# When do you use each one?

- `sort_values` is when you care about high/low values in a particular column
- `sort_index` is when you care about the index, typically because it contains data such dates/times or names.

# This is fine for series... how do we sort data frames?

- `sort_index` works on a data frame in exactly the same way, returning a data frame
- `sort_values` does work, but you need to specify which column (or columns) you want to sort by.

In [14]:
df.sort_index()  # get a new data frame back, based on df, with the index ordered (and the rows dragged along for the ride)

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:00:00,1,2015-06-01 00:06:12,1,1.00,-73.988739,40.756832,1,N,-73.974701,40.757038,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
2015-06-01 00:00:00,2,2015-06-01 00:00:00,2,1.40,-73.987160,40.738972,1,N,-73.976288,40.755573,2,11.5,0.0,0.5,0.00,0.00,0.3,12.30
2015-06-01 00:00:00,2,2015-06-01 00:00:00,1,0.90,-73.984428,40.737209,1,N,-73.979935,40.749088,1,11.5,1.0,0.5,2.00,0.00,0.3,15.30
2015-06-01 00:00:01,2,2015-06-01 00:24:48,1,8.15,-74.006844,40.730572,1,N,-73.946342,40.811508,1,26.5,0.5,0.5,2.50,0.00,0.3,30.30
2015-06-01 00:00:01,1,2015-06-01 00:08:26,3,1.20,-73.981827,40.770767,1,N,-73.994957,40.764378,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-06 16:53:56,1,2015-06-06 17:00:40,1,1.20,-73.992592,40.730629,1,N,-73.998161,40.717072,1,6.5,0.0,0.5,2.19,0.00,0.3,9.49
2015-06-06 16:53:56,1,2015-06-06 17:00:10,1,1.30,-73.973396,40.789967,1,N,-73.958511,40.779106,1,6.5,0.0,0.5,1.45,0.00,0.3,8.75
2015-06-06 16:53:56,2,2015-06-06 17:54:22,1,17.36,-73.790520,40.646461,2,N,-73.969048,40.763062,1,52.0,0.0,0.5,10.66,5.54,0.3,69.00
2015-06-06 16:53:56,2,2015-06-06 16:56:18,1,0.58,-73.949013,40.788616,1,N,-73.952942,40.781727,1,4.0,0.0,0.5,0.95,0.00,0.3,5.75
2015-06-06 16:53:57,1,2015-06-06 16:58:39,1,0.50,-73.968719,40.764427,1,N,-73.965042,40.759476,2,5.0,0.0,0.5,0.00,0.00,0.3,5.80

In [16]:
df.sort_values('trip_distance')  # here, I name the column I want to use for sorting

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:12:13,1,2015-06-01 00:13:47,1,0.00,-74.005714,40.740582,1,N,-74.005417,40.740803,3,3.00,0.5,0.5,0.00,0.00,0.3,4.30
2015-06-04 15:18:09,1,2015-06-04 15:18:09,2,0.00,-74.002953,40.749256,1,N,0.000000,0.000000,2,3.00,0.0,0.5,0.00,0.00,0.3,3.80
2015-06-02 11:23:46,2,2015-06-02 11:24:07,4,0.00,-73.956963,40.766392,1,N,-73.956970,40.766418,2,2.50,0.0,0.5,0.00,0.00,0.3,3.30
2015-06-01 00:08:03,2,2015-06-01 00:08:08,1,0.00,-73.962463,40.755138,2,N,-73.962463,40.755138,1,52.00,0.0,0.5,10.56,0.00,0.3,63.36
2015-06-01 00:07:43,1,2015-06-01 00:07:43,1,0.00,-74.007530,40.740753,1,N,0.000000,0.000000,2,5.00,0.5,0.5,0.00,0.00,0.3,6.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.00,17.29,0.3,137.59
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.00,22.83,0.3,135.13
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.00,5.84,0.3,210.14
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.00,9.75,0.3,160.05
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.00,10.00,0.3,79.96

In [18]:
# What if I want the dropoff times for the 5 longest trips?

(
    df
    .sort_values('trip_distance')   # sorted by trip_distance, largest at the end
    ['tpep_dropoff_datetime']       # get the dropoff times, ignoring everything else
    .tail(5)    # get the 5 final rows (i.e., where trip_distance was greatest)
)

tpep_pickup_datetime
2015-06-04 15:17:25    2015-06-04 17:05:42
2015-06-02 11:21:03    2015-06-02 12:16:47
2015-06-01 00:02:42    2015-06-01 00:03:38
2015-06-01 00:04:50    2015-06-01 01:31:44
2015-06-01 00:00:58    2015-06-01 01:22:05
Name: tpep_dropoff_datetime, dtype: str

# What if we want to sort by more than one column?

Phone books were sorted first by last name, then by first name. How can I?

A general rule of thumb in Pandas is that anywhere you can name one column (with a string), you can name multiple columns (with a list of strings). If I want to sort by two columns, I just name them. The first will be the primary sort key, and the second will be the secondary sort key.

In [19]:
(
    df
    .sort_values(['trip_distance', 'total_amount'])   #if two trips have the same trip_distance, then total_amount decides
)

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-02 11:24:35,2,2015-06-02 11:24:40,1,0.00,0.000000,0.000000,1,N,-73.749077,40.707611,3,-2.50,0.0,-0.5,0.0,0.00,-0.3,-3.30
2015-06-02 11:20:23,2,2015-06-02 11:20:23,2,0.00,-73.937851,40.758236,1,N,0.000000,0.000000,2,1.50,0.0,0.5,0.0,0.00,0.3,2.30
2015-06-02 11:19:46,1,2015-06-02 12:26:33,1,0.00,-73.983200,40.766949,1,N,-73.990410,40.766872,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
2015-06-02 11:24:35,2,2015-06-02 11:24:40,1,0.00,0.000000,0.000000,1,N,-73.749077,40.707611,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
2015-06-02 11:23:46,2,2015-06-02 11:24:07,4,0.00,-73.956963,40.766392,1,N,-73.956970,40.766418,2,2.50,0.0,0.5,0.0,0.00,0.3,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.0,17.29,0.3,137.59
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.0,22.83,0.3,135.13
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.0,5.84,0.3,210.14
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.0,9.75,0.3,160.05
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.0,10.00,0.3,79.96

# Two more methods for getting largest/smallest values

These are really handy methods:

- `nlargest`
- `nsmallest`

These give us the `n` rows in a data frame that are associated with the largest values for a column or the smallest values for a column.

In [20]:
(
    df
    .nlargest(columns='trip_distance', n=10)
)

,VendorID,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
tpep_pickup_datetime,,,,,,,,,,,,,,,,,,
2015-06-01 00:00:58,1,2015-06-01 01:22:05,1,64.60,0.000000,0.000000,5,N,0.000000,0.000000,2,69.66,0.0,0.0,0.00,10.00,0.3,79.96
2015-06-01 00:04:50,1,2015-06-01 01:31:44,1,60.30,-73.994415,40.750603,5,N,-73.420250,41.137344,1,150.00,0.0,0.0,0.00,9.75,0.3,160.05
2015-06-01 00:02:42,1,2015-06-01 00:03:38,1,37.20,-73.550156,41.043472,5,N,-73.550102,41.043495,1,184.00,0.0,0.0,20.00,5.84,0.3,210.14
2015-06-02 11:21:03,2,2015-06-02 12:16:47,1,35.51,-73.789169,40.647758,3,N,-74.176750,40.662647,1,112.00,0.0,0.0,0.00,22.83,0.3,135.13
2015-06-04 15:17:25,2,2015-06-04 17:05:42,1,34.84,-73.787354,40.641670,5,N,-74.177376,40.690781,2,120.00,0.0,0.0,0.00,17.29,0.3,137.59
2015-06-01 00:01:19,2,2015-06-01 00:40:12,1,32.40,-73.781425,40.644905,2,N,-73.974174,40.731441,1,52.00,0.0,0.5,10.56,0.00,0.3,63.36
2015-06-02 11:28:58,1,2015-06-02 12:13:29,1,32.10,-73.873085,40.774124,4,N,-73.957283,41.098221,1,129.00,0.0,0.5,27.05,5.54,0.3,162.39
2015-06-01 00:00:13,1,2015-06-01 00:41:05,1,31.90,-73.875206,40.770382,5,N,-73.549629,41.043552,1,210.00,0.0,0.0,42.05,0.00,0.3,252.35
2015-06-01 00:09:14,1,2015-06-01 01:03:11,1,31.50,-73.802437,40.677372,5,N,-74.255424,40.745316,2,140.00,0.0,0.0,0.00,9.75,0.3,150.05
2015-06-01 00:00:16,2,2015-06-01 00:40:35,2,29.78,-73.781853,40.644711,2,N,-74.006905,40.707958,1,52.00,0.0,0.5,17.50,5.54,0.3,75.84

# Exercise: Olympic records

This exercise uses a CSV file,