# Agenda, day 2

1. Q&A
2. Data frames
    - Create them
    - Indexes and column names
    - Retrieving and setting
    - Methods and attributes we'll want to use
    - `.loc` and mask indexes
3. Creating data frames from files
    - CSV files
    - Excel
    - JSON
    - Retrieving data from the Internet

# Data frames

If a series is a 1D data structure (with values and an index), then a data frame is a 2D data structure, much like an Excel spreadsheet. It also has an index (identifying the rows) and columns (identifying the ... columns).

Each column in a data frame is actually a series in disguise!

In [1]:
# quick and dirty creation of a data frame, using a list of lists

import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])

In [3]:
df

     0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

- Rows are 0,1,2,3
- Columns are 0, 1, 2

This is because we didn't name them.

Notice also that it's OK for the rows and columns to have the same names (or in this case, numbers).

In [4]:
df.index   # show me the rows

RangeIndex(start=0, stop=4, step=1)

In [5]:
df.columns  # show me the columns

RangeIndex(start=0, stop=3, step=1)

In [6]:
# I might want to set either the index or the column names
# we saw with a series that we can pass index= and then a list
# the same is true with a data frame, except we can also say columns= and give a list of column names

df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [7]:
# just like with a series, we can retrieve via the index using .loc (and .iloc, by position)

df.loc['a']

x    10
y    20
z    30
Name: a, dtype: int64

In [8]:
df.loc['c']

x    70
y    80
z    90
Name: c, dtype: int64

In [9]:
# I can even use fancy indexing to get more than one row

df.loc[['a', 'c']]  # pass a list of indexes for fancy indexing

    x   y   z
a  10  20  30
c  70  80  90

In [10]:
# I can even use a slice

df.loc['a':'c']   # no inner list here, because it's a slice

    x   y   z
a  10  20  30
b  40  50  60
c  70  80  90

In [11]:
# I can still use my friend iloc, to go by location

df.iloc[0]

x    10
y    20
z    30
Name: a, dtype: int64

In [12]:
df.iloc[2]

x    70
y    80
z    90
Name: c, dtype: int64

In [14]:
df.iloc[[0, 2]]

    x   y   z
a  10  20  30
c  70  80  90

In [15]:
df.iloc[0:2]  # unlike .loc, this is up to and *not* including, as per Python in general

    x   y   z
a  10  20  30
b  40  50  60

# But ... what about the columns?

We can retrieve from columns using `[]`. That is, if you use `.loc`, you get rows (via the index). But if you use `[]`, you get columns. 

This is why I told you last week not to use `[]` to retrieve rows, because you'll get confused.

In [16]:
df['x']  # this returns the x column in df

a     10
b     40
c     70
d    100
Name: x, dtype: int64

In [17]:
# can I use fancy indexing with columns? Yes!

df[['x', 'z']]   # list inside of []

     x    z
a   10   30
b   40   60
c   70   90
d  100  120

In [18]:

df = DataFrame([[10, 20.1, 30],     # list of lists
                [40, 50.2, 60],
                [70, 80.3, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x      y    z
a   10   20.1   30
b   40   50.2   60
c   70   80.3   90
d  100  110.0  120

In [19]:
df.dtypes  # what dtypes do we have?

x      int64
y    float64
z      int64
dtype: object

In [20]:
# what happens if I now retrieve row a?

df.loc['a']   # we get a series back, with a dtype of float64 -- the integers were silently changed for this temporary, in-memory series

x    10.0
y    20.1
z    30.0
Name: a, dtype: float64

# Exercise: Grocery store

1. Create a data frame describing products in a grocery store. The columns will be `product` (a string), `price` (an int), and `department` (also a string).
2. Add 5 products in your store. Each product will be one row in your data frame.
3. Retrieve the products at positions 0 and 3.
4. Retrieve just the `price` column. What is the mean price of items in your store?

In [21]:
df

     x      y    z
a   10   20.1   30
b   40   50.2   60
c   70   80.3   90
d  100  110.0  120

In [22]:
df.values

array([[ 10. ,  20.1,  30. ],
       [ 40. ,  50.2,  60. ],
       [ 70. ,  80.3,  90. ],
       [100. , 110. , 120. ]])

In [24]:
df = DataFrame([['apple', 5, 'produce'],
                ['bananas', 3, 'produce'],
                ['computer', 500, 'electronics'],
                ['diary', 20, 'books'],
                ['elephant', 100, 'pets']],
               index=[123, 456, 789, 234, 678],
               columns='product price department'.split())
df

      product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets

In [25]:
df.dtypes

product         str
price         int64
department      str
dtype: object

In [26]:
df.iloc[[0, 3]]

    product  price department
123   apple      5    produce
234   diary     20      books

In [28]:
df.loc[[123, 234]]

    product  price department
123   apple      5    produce
234   diary     20      books

In [29]:
df['price']

123      5
456      3
789    500
234     20
678    100
Name: price, dtype: int64

In [30]:
df['price'].mean()   # invoke the mean method on a series

np.float64(125.6)

# Another way to retrieve columns

I much (MUCH) prefer to retrieve columns in this way, as I've shown you, with `[]`. But there is another way, namely dot notation. Just put the name of the column after the name of the data frame and a dot, as if it's an attribute of the data frame.

In [32]:
df.price

123      5
456      3
789    500
234     20
678    100
Name: price, dtype: int64

In [33]:
df.department

123        produce
456        produce
789    electronics
234          books
678           pets
Name: department, dtype: str

In [34]:
df.product

<bound method DataFrame.prod of       product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets>

Dot syntax works great, until/unless:

- Your column has the same name as a Pandas method or attribute, in which case the Pandas value gets priority over yours
- If the column contains spaces or other characters that aren't legal in Python attribute names, then they won't work

# What if I want to assign a new column to our data frame?

We can do this by assigning to a new column in the data frame -- just make sure that it has the right number of elements.

In [35]:
df

      product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets

In [36]:
df['letter'] = ['a', 'b', 'c', 'd', 'e']   #adds a new column

In [37]:
df

      product  price   department letter
123     apple      5      produce      a
456   bananas      3      produce      b
789  computer    500  electronics      c
234     diary     20        books      d
678  elephant    100         pets      e

In [38]:
# what happens if I try to add a column with the wrong number of values?

df['letter2'] = ['a', 'b', 'c', 'd']

ValueError: Length of values (4) does not match length of index (5)

In [39]:
df

      product  price   department letter
123     apple      5      produce      a
456   bananas      3      produce      b
789  computer    500  electronics      c
234     diary     20        books      d
678  elephant    100         pets      e

# What if you want to replace an existing column with other values?

Answer: Just assign to the column. The new one will replace the old one.

In [40]:
df['letter'] = ['aaa', 'bbb', 'ccc', 'ddd', 'eee']   # because we're assigning to an existing column, it is replaced

In [41]:
df

      product  price   department letter
123     apple      5      produce    aaa
456   bananas      3      produce    bbb
789  computer    500  electronics    ccc
234     diary     20        books    ddd
678  elephant    100         pets    eee

Many times, we'll want to do this to calculate values based on existing columns.

In [42]:
tax_rate = 0.1

df['price'] * tax_rate    # series * a scalar = broadcasting

123     0.5
456     0.3
789    50.0
234     2.0
678    10.0
Name: price, dtype: float64

In [43]:
df['product_tax'] = df['price'] * tax_rate

In [44]:
df

      product  price   department letter  product_tax
123     apple      5      produce    aaa          0.5
456   bananas      3      produce    bbb          0.3
789  computer    500  electronics    ccc         50.0
234     diary     20        books    ddd          2.0
678  elephant    100         pets    eee         10.0

In [45]:
df['total_price'] = df['price'] + df['product_tax']

In [46]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [48]:
df2 = df.copy()   #get a copy of df's data, but without sharing it

In [49]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [50]:
df2

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [52]:
df2['total_price'] = df2['price'] + df2['price'] + df2['product_tax']

In [53]:
df2

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5         10.5
456   bananas      3      produce    bbb          0.3          6.3
789  computer    500  electronics    ccc         50.0       1050.0
234     diary     20        books    ddd          2.0         42.0
678  elephant    100         pets    eee         10.0        210.0

In [54]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

In [55]:
# the assign method adds a new column to a temporary data frame that it returns

In [56]:
df

      product  price   department letter  product_tax  total_price
123     apple      5      produce    aaa          0.5          5.5
456   bananas      3      produce    bbb          0.3          3.3
789  computer    500  electronics    ccc         50.0        550.0
234     diary     20        books    ddd          2.0         22.0
678  elephant    100         pets    eee         10.0        110.0

# More complex queries

Let's say that I want to retrieve from my data frame based on a particular column's values -- but I don't want that column's values, rather I want to use one column as my mask index, and retrieve from another.

For example, I want the mean price of all items with a product_tax > 5.

The way to do this is with `.loc`, the 2-argument edition.

- The first argument to `.loc` (mandatory) is the row selector
    - one index value
    - a list of index values ("fancy indexing")
    - a slice
    - a boolean series for use as a "mask index"
- The second (optional) argument to `.loc` is a column selector
    - one column name
    - a list of column names

In [57]:
df.loc[123, 'department']   # row selector = 123, column selector = 'department'

'produce'

In [59]:
# I'm going to spread these out, using "method chaining"

(
    df
    .loc[
        123,              # index, the row selector
        'department'      # column name, the column selector
    ]

)

'produce'

In [61]:
# I can ask for more than one row


(
    df
    .loc[
        [123, 456],        # index, the row selector -- fancy indexing
        'department'      # column name, the column selector
    ]

)

123    produce
456    produce
Name: department, dtype: str

In [62]:
# I can ask for more than one column

(
    df
    .loc[
        [123, 456],        # index, the row selector -- fancy indexing
        ['price', 'department']      # column name, the column selector
    ]

)

     price department
123      5    produce
456      3    produce

In [66]:
# I can use a boolean series to retrieve certain rows
# get the mean price, where the product tax is > 5

(
    df
    .loc[
        df['product_tax'] > 5,        # index, the row selector -- fancy indexing
        'price'      # column name, the column selector
    ]
    .mean()  

)

np.float64(300.0)

# Exercise: Family members

1. Create a data frame with 5 family members (or friends, or make them up). Each row represents one person. The columns will be named `name`, `age`, and `shoesize`.
2. What is the mean `shoesize` for all members of your family?
3. What are the `min` and `max` values of `age` for your family?
4. Retrieve all names and shoe sizes.
5. Retrieve the age and name of the person in row 0.

In [67]:
df = DataFrame([['Reuven', 56, 46],
                ['B', 54, 40],
                ['C', 25, 40],
                ['D', 23, 40],
                ['E', 20, 44]],
               columns=['name', 'age', 'shoesize'])
df

     name  age  shoesize
0  Reuven   56        46
1       B   54        40
2       C   25        40
3       D   23        40
4       E   20        44

In [68]:
df['shoesize'].mean()

np.float64(42.0)

In [69]:
df['shoesize'].median()

np.float64(40.0)

In [70]:
df['age'].min()

np.int64(20)

In [71]:
df['age'].max()

np.int64(56)

In [72]:
df['age'].describe()

count     5.000000
mean     35.600000
std      17.812917
min      20.000000
25%      23.000000
50%      25.000000
75%      54.000000
max      56.000000
Name: age, dtype: float64

In [73]:
df['age'].agg(['min', 'max'])

min    20
max    56
Name: age, dtype: int64

In [74]:
# Retrieve all names and shoe sizes.

df[['name', 'shoesize']]   # fancy indexing on the column names

     name  shoesize
0  Reuven        46
1       B        40
2       C        40
3       D        40
4       E        44

In [76]:
# Retrieve the age and name of the person in row 0.

(
    df
    .loc[
            0,                 # row selector
            ['name', 'age']    # column selector
        ]
)

name    Reuven
age         56
Name: 0, dtype: object

# Next up

1. Useful methods and attributes
2. Boolean/mask indexes with data frames

# Methods and attributes

Remember that Pandas has a *huge* number of methods and attributes.

Most of the methods that you learned about with a series are *also* going to work on a data frame.

- If the series version returns a single value, then the data frame version will return a series (one value for each column)
- If the series version returns a series, then the data frame version will return a data frame (one series for each column)

In [77]:
df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [78]:
df['x'].mean()  # get column x, and calculate the mean

np.float64(55.0)

In [79]:
df.mean()    #mean from each column

x    55.0
y    65.0
z    75.0
dtype: float64

In [80]:
df['y'].max()  # max from y

np.int64(110)

In [81]:
df.max()  # the max value from each column

x    100
y    110
z    120
dtype: int64

In [82]:
df['z'].describe()   # this gives us back a series, describing the column

count      4.000000
mean      75.000000
std       38.729833
min       30.000000
25%       52.500000
50%       75.000000
75%       97.500000
max      120.000000
Name: z, dtype: float64

In [83]:
df.describe()    # this gives us back a data frame, describing each of the columns

                x           y           z
count    4.000000    4.000000    4.000000
mean    55.000000   65.000000   75.000000
std     38.729833   38.729833   38.729833
min     10.000000   20.000000   30.000000
25%     32.500000   42.500000   52.500000
50%     55.000000   65.000000   75.000000
75%     77.500000   87.500000   97.500000
max    100.000000  110.000000  120.000000

# Setting the index

One thing that we didn't really have with a series is the ability to set and remove the index. We could assign to the `.index` attribute, but it's not that same as a data frame.

In a data frame, we can move a column to be the index with the `set_index` method. We can push the index into being a regular column with the `reset_index` method.

**In neither case does the data frame really change!** The default in Pandas is to return a new value, based on the old one, with the change in place. But the change doesn't really happen on the original data frame.

In [84]:
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [85]:
df.set_index('x')

       y    z
x
10    20   30
40    50   60
70    80   90
100  110  120

In [87]:
# have I really changed df? No!

df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [88]:
# if I want the set_index to be permanent, I assign the data frame I got back from set_index to df

df = df.set_index('x')

In [89]:
df

       y    z
x
10    20   30
40    50   60
70    80   90
100  110  120

In [90]:
# to reverse this, and turn the index back into a regular (named) column, we use reset_index

df.reset_index()

     x    y    z
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

In [91]:
# just like set_index, reset_index doesn't really change anything -- it returns a new data frame

df = df.reset_index()
df

     x    y    z
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

In [92]:
df = df.set_index('y')
df

       x    z
y
20    10   30
50    40   60
80    70   90
110  100  120

Pandas people use the index a lot, because a lot of methods use the index, and are dependent on it.

In [93]:
df = df.reset_index()

In [94]:
df

     y    x    z
0   20   10   30
1   50   40   60
2   80   70   90
3  110  100  120

In [98]:
# method chaining in action!

(
    df
    .set_index('x')
    .loc[[10, 70],   # row selector
         'y']        # column selector  -- this means, "give me column y where the row has index 10 or 70"
)

x
10    20
70    80
Name: y, dtype: int64

# What about `NaN`?

Remember `NaN`, the "not a number" value that indicates we don't have a value?

On a series:

- `dropna` returns a new series based on our existing one, but without the `NaN` values
- `fillna` returns a new series based on our existing one, but replacing all `NaN` values with something we specify

These methods, on data frames, work a bit differently:

- `dropna` returns a new data frame based on our existing one, but without any row containing a `NaN` value -- a single `NaN` value in the row will remove the whole row!
- `fillna` returns a new data frame based on our existing on. You can fill with a single value (which will fill all `NaN` values) or with a series whose index matches our columns -- and then each column's `NaN` can be filled in differently.

In [99]:
df

     y    x    z
0   20   10   30
1   50   40   60
2   80   70   90
3  110  100  120

In [100]:
# add some nan values

import numpy as np

In [102]:
df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))


df.loc['b', 'y'] = np.nan
df.loc['a', 'z'] = np.nan
df.loc['a', 'x'] = np.nan
df.loc['d', 'y'] = np.nan

df

       x     y      z
a    NaN  20.0    NaN
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [103]:
df.dtypes

x    float64
y    float64
z    float64
dtype: object

In [104]:
df.dropna()  # what will we get back?

      x     y     z
c  70.0  80.0  90.0

The good news with the above query is that we now have 100% rock-solid data. No NaNs!

The bad news is that we got rid of 75% of our data.

You can decide that some columns are more important than others, and should/shouldn't be included in the NaN decision. You can also decide that it's OK to have *some* NaN in a row, but maybe not everything.

In [105]:
df.dropna(subset=['x'])  # only pay attention to NaN in x

       x     y      z
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

In [107]:
df.dropna(thresh=2)  # any row with at least 2 good values will be returned

       x     y      z
b   40.0   NaN   60.0
c   70.0  80.0   90.0
d  100.0   NaN  120.0

# Exercise: More with groceries

1. (Re)define the data frame with groceries.
2. Set the index to be the product names.
3. Retrieve 3 items via the index, and find the min/max prices for them.
4. Set the index to be the department. Find the mean price for items in one department.

In [108]:
df = DataFrame([['apple', 5, 'produce'],
                ['bananas', 3, 'produce'],
                ['computer', 500, 'electronics'],
                ['diary', 20, 'books'],
                ['elephant', 100, 'pets']],
               index=[123, 456, 789, 234, 678],
               columns='product price department'.split())
df

      product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets

In [113]:
(
    df
    .set_index('product')
    .loc[ ['apple', 'bananas', 'diary'] ,   # row selector
         'price'  ]    # column selector
    .agg(['min', 'max'])
)

min     3
max    20
Name: price, dtype: int64

In [117]:
(
    df
    .set_index('department')
    .loc['produce',    # row selector
        'price']       # column
    .mean()
)

np.float64(4.0)

# Boolean/mask indexes

Remember:

- We invoke, via broadcasting, an operator on a series
- That returns a series of booleans (`True` and `False`)
- We apply that boolean series to our series with `.loc`
- Only those values that correspond to `True` are returned -- the rest are dropped

In [118]:
s = Series([10, 20, 30])

s.loc[[True, False, True]]

0    10
2    30
dtype: int64

In [119]:
s.loc[ s >= 20 ]

1    20
2    30
dtype: int64

In [120]:
df

      product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets

In [122]:
# we can use df.loc, giving it a boolean series as a mask index -- which it'll apply to every row

df.loc[    df['price'] > 30  ]

      product  price   department
789  computer    500  electronics
678  elephant    100         pets

In [124]:
# as of Pandas 3.0, we have a new, special syntax for this kind of thing, using pd.col(NAME) instead of df['NAME']

(
    df
    .loc[ pd.col('price') > 30 ]   # this is considered more modern
)

      product  price   department
789  computer    500  electronics
678  elephant    100         pets

# Exercise: Grocery reports

1. Re-use the grocery data (again!)
2. Add a new column, `pct_tax`, which is the percentage tax applied to each item. Vary it according to department.
3. Add a new column, `total_price`, which includes the tax.
4. Retrieve items where `total_price` > 50
5. Retrieve products where `department` is `produce`.

In [125]:
df

      product  price   department
123     apple      5      produce
456   bananas      3      produce
789  computer    500  electronics
234     diary     20        books
678  elephant    100         pets

In [126]:
df['pct_tax'] = [0.05, 0.05, 0.1, 0.01, 0.3]

In [127]:
df

      product  price   department  pct_tax
123     apple      5      produce     0.05
456   bananas      3      produce     0.05
789  computer    500  electronics     0.10
234     diary     20        books     0.01
678  elephant    100         pets     0.30

In [128]:
df['total_price']  = df['price'] + (df['price'] * df['pct_tax'])
df['total_price']

123      5.25
456      3.15
789    550.00
234     20.20
678    130.00
Name: total_price, dtype: float64

In [130]:
df.loc[   df['total_price'] > 50  ]

      product  price   department  pct_tax  total_price
789  computer    500  electronics      0.1        550.0
678  elephant    100         pets      0.3        130.0

In [134]:
# Retrieve products where department is produce.

(
    df
    .loc
    [ df['department'] == 'produce' ]  # row selector
)

     product  price department  pct_tax  total_price
123    apple      5    produce     0.05         5.25
456  bananas      3    produce     0.05         3.15

# Next up

1. More with boolean indexes/methods
2. Real-world data with files!

Download this zipfile, if you can: https://files.lerner.co.il/data-science-exercise-files.zip

In [136]:
# redo our previous exercise, using the new pd.col syntax

# old: df.loc[   df['total_price'] > 50  ]

df.loc[   pd.col('total_price') > 50  ]

      product  price   department  pct_tax  total_price
789  computer    500  electronics      0.1        550.0
678  elephant    100         pets      0.3        130.0

In [137]:
(
    df
    .loc
    [ pd.col('department') == 'produce' ]  # row selector
)

     product  price department  pct_tax  total_price
123    apple      5    produce     0.05         5.25
456  bananas      3    produce     0.05         3.15

In [138]:
df

      product  price   department  pct_tax  total_price
123     apple      5      produce     0.05         5.25
456   bananas      3      produce     0.05         3.15
789  computer    500  electronics     0.10       550.00
234     diary     20        books     0.01        20.20
678  elephant    100         pets     0.30       130.00

In [139]:
(
    df
    .loc[ pd.col('department') == 'produce']
    .loc[ pd.col('total_price') > 3 ]
)

     product  price department  pct_tax  total_price
123    apple      5    produce     0.05         5.25
456  bananas      3    produce     0.05         3.15

In [145]:
# what is the mean price for all products with a tax of 5% or more, and a total price of 25 or more?

(
    df
    .loc[ pd.col('pct_tax') >= 0.05 ]
    .loc[ pd.col('total_price') >= 25 ]
    ['price']   
    .mean()
)

np.float64(300.0)

In [149]:
# we can simplifily this a bit by using the 2-argument version of .loc in the query

(
    df
    .loc[ pd.col('pct_tax') >= 0.05 ]
    .loc[ pd.col('total_price') >= 25 ]
)

      product  price   department  pct_tax  total_price
789  computer    500  electronics      0.1        550.0
678  elephant    100         pets      0.3        130.0

In [150]:
# we can simplifily this a bit by using the 2-argument version of .loc in the query

(
    df
    .loc[ pd.col('pct_tax') >= 0.05 ]
    .loc[ pd.col('total_price') >= 25, 'price' ]
    .mean()
)

np.float64(300.0)

# Other useful methods

Some methods that we used on series come in handy here, too:

- `head` -- first n rows
- `tail` -- last n rows
- `value_counts` -- you'll almost certainly want to use it on a single column

In [152]:
# we get the results of value_counts on every combination of the two named columns

df[['price', 'total_price']].value_counts()

price  total_price
5      5.25           1
3      3.15           1
500    550.00         1
20     20.20          1
100    130.00         1
Name: count, dtype: int64

# `df.info` -- info about our data frame

If you run `df.info`, you'll find out about columns, rows, and memory usage

In [153]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 123 to 678
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product      5 non-null      str
 1   price        5 non-null      int64
 2   department   5 non-null      str
 3   pct_tax      5 non-null      float64
 4   total_price  5 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 307.0 bytes

# Files!

When I started to work with data, I assumed there was a standard way to share data files in a robust way. Answer: NOPE! We still mostly use CSV (comma-separated values) and Excel files.

- CSV has one record per line, with commas (or something else) separating fields. This is a text file, which means that Pandas needs to guess (or we need to hint) regarding what types of values to expect.
- Excel is closer to binary in many ways, which can mean that we'll get values without guessing. However, Excel is often limited in how much data it can contain. Also, it can be very slow to load.

Pandas has facilities to both read and write 30 or so different formats. The two most common ones are still CSV and Excel.

To read a file into a Pandas data frame, you'll want to use a `pd.read_*` method. It's not a data-frame method, because we're getting a new data frame from it. Rather, it's a top-level `pd` method.

In [154]:
df = pd.read_csv('taxi.csv')
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2015-06-02 11:19:29,2015-06-02 11:47:52,1,1.63,-73.954430,40.764141,1,N,-73.974754,40.754093,2,17.0,0.0,0.5,0.00,0.0,0.3,17.80
1,2,2015-06-02 11:19:30,2015-06-02 11:27:56,1,0.46,-73.971443,40.758942,1,N,-73.978539,40.761909,1,6.5,0.0,0.5,1.00,0.0,0.3,8.30
2,2,2015-06-02 11:19:31,2015-06-02 11:30:30,1,0.87,-73.978111,40.738434,1,N,-73.990273,40.745438,1,8.0,0.0,0.5,2.20,0.0,0.3,11.00
3,2,2015-06-02 11:19:31,2015-06-02 11:39:02,1,2.13,-73.945892,40.773529,1,N,-73.971527,40.760330,1,13.5,0.0,0.5,2.86,0.0,0.3,17.16
4,1,2015-06-02 11:19:32,2015-06-02 11:32:49,1,1.40,-73.979088,40.776772,1,N,-73.982162,40.758999,2,9.5,0.0,0.5,0.00,0.0,0.3,10.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,1,2015-06-01 00:12:59,2015-06-01 00:24:18,1,2.70,-73.947792,40.814972,1,N,-73.973358,40.783638,2,11.0,0.5,0.5,0.00,0.0,0.3,12.30
9995,1,2015-06-01 00:12:59,2015-06-01 00:28:16,1,4.50,-74.004066,40.747818,1,N,-73.953758,40.779285,1,16.0,0.5,0.5,3.00,0.0,0.3,20.30
9996,2,2015-06-01 00:13:00,2015-06-01 00:37:25,1,5.59,-73.994377,40.766102,1,N,-73.903206,40.750546,2,21.0,0.5,0.5,0.00,0.0,0.3,22.30
9997,2,2015-06-01 00:13:02,2015-06-01 00:19:10,6,1.54,-73.978302,40.748531,1,N,-73.989166,40.762852,2,6.5,0.5,0.5,0.00,0.0,0.3,7.80
9998,1,2015-06-01 00:13:04,2015-06-01 00:36:33,1,5.80,-73.983215,40.726414,1,N,-73.924133,40.701645,1,21.0,0.5,0.5,4.45,0.0,0.3,26.75

In [155]:
df.describe()

,VendorID,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000
mean,1.516652,1.659466,3.158511,-73.014956,40.226521,1.045105,-73.054699,40.248644,1.407741,14.415892,0.118212,0.497450,1.818059,0.400433,0.299790,17.552472
std,0.499748,1.333306,4.037516,8.347871,4.599169,0.302132,8.186847,4.510520,0.501911,12.442624,0.214794,0.037667,2.634469,1.665170,0.010816,15.137990
min,1.000000,0.000000,0.000000,-74.186302,0.000000,1.000000,-74.277367,0.000000,1.000000,-7.000000,-0.500000,-0.500000,0.000000,0.000000,-0.300000,-7.800000
25%,1.000000,1.000000,1.000000,-73.990997,40.738556,1.000000,-73.990261,40.738478,1.000000,7.000000,0.000000,0.500000,0.000000,0.000000,0.300000,8.800000
50%,2.000000,1.000000,1.700000,-73.979774,40.755909,1.000000,-73.978256,40.756340,1.000000,10.500000,0.000000,0.500000,1.000000,0.000000,0.300000,12.800000
75%,2.000000,2.000000,3.300000,-73.963001,40.770012,1.000000,-73.961311,40.771044,2.000000,17.000000,0.000000,0.500000,2.460000,0.000000,0.300000,19.800000
max,2.000000,6.000000,64.600000,0.000000,41.064606,5.000000,0.000000,41.137344,4.000000,250.000000,1.000000,0.500000,42.050000,70.000000,0.300000,252.350000

# Exercise: Weird taxi rides

1. Read `taxi.csv` into a Pandas data frame.
2. How many rides traveled 0 miles (`trip_distance`).
3. How much, on average, did people pay (`total_amount`) for such rides?
4. How many rides cost <= 0 dollars (`total_amount`)? How far (`trip_distance`) did people travel on such a trip?
5. How many rides had 0 passengers (`passenger_count`)? Give the mean `trip_distance` and `total_amount` for such trips.