# Agenda, day 2

1. Q&A
2. Data frames
    - Create them
    - Indexes and column names
    - Retrieving and setting
    - Methods and attributes we'll want to use
    - `.loc` and mask indexes
3. Creating data frames from files
    - CSV files
    - Excel
    - JSON
    - Retrieving data from the Internet

# Data frames

If a series is a 1D data structure (with values and an index), then a data frame is a 2D data structure, much like an Excel spreadsheet. It also has an index (identifying the rows) and columns (identifying the ... columns).

Each column in a data frame is actually a series in disguise!

In [1]:
# quick and dirty creation of a data frame, using a list of lists

import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])

In [3]:
df

     0    1    2
0   10   20   30
1   40   50   60
2   70   80   90
3  100  110  120

- Rows are 0,1,2,3
- Columns are 0, 1, 2

This is because we didn't name them.

Notice also that it's OK for the rows and columns to have the same names (or in this case, numbers).

In [4]:
df.index   # show me the rows

RangeIndex(start=0, stop=4, step=1)

In [5]:
df.columns  # show me the columns

RangeIndex(start=0, stop=3, step=1)

In [6]:
# I might want to set either the index or the column names
# we saw with a series that we can pass index= and then a list
# the same is true with a data frame, except we can also say columns= and give a list of column names

df = DataFrame([[10, 20, 30],     # list of lists
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x    y    z
a   10   20   30
b   40   50   60
c   70   80   90
d  100  110  120

In [7]:
# just like with a series, we can retrieve via the index using .loc (and .iloc, by position)

df.loc['a']

x    10
y    20
z    30
Name: a, dtype: int64

In [8]:
df.loc['c']

x    70
y    80
z    90
Name: c, dtype: int64

In [9]:
# I can even use fancy indexing to get more than one row

df.loc[['a', 'c']]  # pass a list of indexes for fancy indexing

    x   y   z
a  10  20  30
c  70  80  90

In [10]:
# I can even use a slice

df.loc['a':'c']   # no inner list here, because it's a slice

    x   y   z
a  10  20  30
b  40  50  60
c  70  80  90

In [11]:
# I can still use my friend iloc, to go by location

df.iloc[0]

x    10
y    20
z    30
Name: a, dtype: int64

In [12]:
df.iloc[2]

x    70
y    80
z    90
Name: c, dtype: int64

In [14]:
df.iloc[[0, 2]]

    x   y   z
a  10  20  30
c  70  80  90

In [15]:
df.iloc[0:2]  # unlike .loc, this is up to and *not* including, as per Python in general

    x   y   z
a  10  20  30
b  40  50  60

# But ... what about the columns?

We can retrieve from columns using `[]`. That is, if you use `.loc`, you get rows (via the index). But if you use `[]`, you get columns. 

This is why I told you last week not to use `[]` to retrieve rows, because you'll get confused.

In [16]:
df['x']  # this returns the x column in df

a     10
b     40
c     70
d    100
Name: x, dtype: int64

In [17]:
# can I use fancy indexing with columns? Yes!

df[['x', 'z']]   # list inside of []

     x    z
a   10   30
b   40   60
c   70   90
d  100  120

In [18]:

df = DataFrame([[10, 20.1, 30],     # list of lists
                [40, 50.2, 60],
                [70, 80.3, 90],
                [100, 110, 120]],
               index=list('abcd'),
               columns=list('xyz'))
df

     x      y    z
a   10   20.1   30
b   40   50.2   60
c   70   80.3   90
d  100  110.0  120

In [19]:
df.dtypes  # what dtypes do we have?

x      int64
y    float64
z      int64
dtype: object

In [20]:
# what happens if I now retrieve row a?

df.loc['a']   # we get a series back, with a dtype of float64 -- the integers were silently changed for this temporary, in-memory series

x    10.0
y    20.1
z    30.0
Name: a, dtype: float64

# Exercise: Grocery store

1. Create a data frame describing products in a grocery store. The columns will be `product` (a string), `price` (an int), and `department` (also a string).
2. Add 5 products in your store. Each product will be one row in your data frame.
3. Retrieve the products at positions 0 and 3.
4. Retrieve just the `price` column. What is the mean price of items in your store?

In [21]:
df

     x      y    z
a   10   20.1   30
b   40   50.2   60
c   70   80.3   90
d  100  110.0  120

In [22]:
df.values

array([[ 10. ,  20.1,  30. ],
       [ 40. ,  50.2,  60. ],
       [ 70. ,  80.3,  90. ],
       [100. , 110. , 120. ]])